spring:
  data:
    mongodb:
      host: 192.168.115.118
      port: 27017
      database: article
    redis:
      host: 192.168.115.118
      port: 6379


logging:
  level:
    org.springframework.data.mongodb.core: debug
